version: '3'
services:
  nginx:
    build: .
    ports:
      - '8443:443'
  keycloak:
    image: 'jboss/keycloak'
    environment:
      - KEYCLOAK_PASSWORD=pass
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true
